<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Central (shared-database) schema for a KNOWLEDGE ENTRY CHUNK — the unit of RETRIEVAL. The
 * own-database mirror omits workspace_id.
 *
 * An entry may be 40k characters; one embedding over all of it averages away exactly the specifics a
 * retrieval query is looking for. So an entry is split into overlapping passages and each passage
 * gets its own vector. This table is where the vectors live — deliberately NOT on knowledge_entries.
 *
 * `ordinal` is the chunk's position in its entry and is unique per entry, which makes (entry,
 * ordinal) a stable citation address: B2b's link `evidence` records the two ordinals that made a
 * similarity edge, and a UI can point at the exact passage instead of the whole entry.
 *
 * `digest` is the sha256 of the chunk's own text, so a re-index can skip the passages an edit did not
 * touch instead of re-embedding (and re-paying for) the whole entry.
 *
 * `knowledge_base_id` is denormalized so a base-scoped vector search filters without joining a table
 * the ANN scan would otherwise have to reach through.
 *
 * The `embedding` column and its HNSW index are raw DDL: Laravel's Blueprint has no pgvector type.
 * The index uses `vector_cosine_ops` because cosine distance (`<=>`) is what normalized text
 * embeddings are compared with; m=16 / ef_construction=64 are pgvector's defaults, which are the
 * right starting point until a real base exists to tune against.
 *
 * DIMENSION: 1536 is hardcoded here, matching config('knowledge.embedding.dimensions') (the native
 * width of text-embedding-3-small). It is NOT read from config on purpose — a schema that changes
 * shape with an env var is a schema nobody can reason about. Changing the model width therefore means
 * a real migration that re-creates the column and re-indexes everything, and KnowledgeSchemaTest pins
 * the config to this number so the drift is caught in CI instead of at query time.
 *
 * Chunks are DERIVED data: no soft deletes (a deleted chunk is regenerated by re-indexing) and a
 * cascade from the entry.
 */
return new class extends Migration
{
    /** Must match config('knowledge.embedding.dimensions') — see the class docblock. */
    private const DIMENSIONS = 1536;

    public function up(): void
    {
        Schema::create('knowledge_entry_chunks', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->uuid('workspace_id')->nullable()->index();

            $table->foreignUuid('knowledge_entry_id')->constrained('knowledge_entries')->cascadeOnDelete();

            // Denormalized for base-scoped retrieval (see the class docblock).
            $table->uuid('knowledge_base_id')->index();

            $table->smallInteger('ordinal');

            // The heading trail the passage sits under ("Cennik > Rabaty"), prepended to the embedded
            // text so a passage carries its context instead of floating free.
            $table->string('heading_path', 500)->nullable();

            $table->text('content');

            // Where the passage sits in the entry's content — lets a citation highlight the source.
            $table->integer('char_start');
            $table->integer('char_length');

            $table->char('digest', 64)->index();

            // The provider/model that produced `embedding`, so a model swap is detectable per row.
            $table->string('embedding_model')->nullable();
            $table->timestamp('indexed_at')->nullable();

            $table->timestamps();

            // The stable citation address + the "one row per passage" guarantee a re-index relies on.
            $table->unique(['knowledge_entry_id', 'ordinal']);
        });

        if (DB::connection()->getDriverName() !== 'pgsql') {
            return;
        }

        DB::statement('ALTER TABLE knowledge_entry_chunks ADD COLUMN embedding vector(' . self::DIMENSIONS . ')');

        DB::statement(
            'CREATE INDEX knowledge_entry_chunks_embedding_hnsw ON knowledge_entry_chunks '
            . 'USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)'
        );
    }

    public function down(): void
    {
        // The index and the raw column go with the table.
        Schema::dropIfExists('knowledge_entry_chunks');
    }
};
