<?php

namespace App\Modules\Knowledge\Models;

use App\Models\AbstractModel;
use App\Traits\TenantAware;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * One embedded PASSAGE of a knowledge entry — the unit of retrieval, and the only place vectors live.
 *
 * `(knowledge_entry_id, ordinal)` is a stable citation address: a similarity edge records which
 * ordinals matched, so a suggestion can be inspected at the passage level instead of taken on faith.
 * `digest` is the sha256 of this passage's own text, which lets a re-index re-embed only what
 * actually changed.
 *
 * The `embedding` column is a raw pgvector `vector(1536)` with no Eloquent cast: reading it back as a
 * PHP array is never what a caller wants (the comparison happens IN Postgres, via the `<=>` cosine
 * operator against the HNSW index), and casting it would quietly pull megabytes of floats into
 * memory on any plain `get()`. {@see scopeWithoutEmbedding()} is the safe default projection for
 * anything that lists chunks; B2a writes the column with an explicit expression.
 *
 * Derived data: no soft deletes and no creator. A lost chunk is regenerated by re-indexing, and it
 * has no author distinct from the entry it was cut from.
 */
class KnowledgeEntryChunk extends AbstractModel
{
    use HasFactory, HasUuids, TenantAware;

    protected $table = 'knowledge_entry_chunks';

    protected $fillable = [
        'knowledge_entry_id',
        'knowledge_base_id',
        'ordinal',
        'heading_path',
        'content',
        'char_start',
        'char_length',
        'digest',
        'embedding_model',
        'indexed_at',
    ];

    protected $casts = [
        'ordinal' => 'integer',
        'char_start' => 'integer',
        'char_length' => 'integer',
        'indexed_at' => 'datetime',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];

    public function entry(): BelongsTo
    {
        return $this->belongsTo(KnowledgeEntry::class, 'knowledge_entry_id');
    }

    /**
     * Passages that are REALLY indexed: they carry a vector, AND that vector was produced by the
     * embedding model configured right now.
     *
     * The model check is the half that is easy to leave out and expensive to leave out. Vectors from
     * two different embedding models share no coordinate system, so counting an old model's leftover
     * vector as "indexed" would report an entry as complete while half of it was unsearchable — and
     * nothing downstream could detect it, because a meaningless similarity score looks exactly like a
     * low one.
     *
     * This is the ONE definition, used by the indexer to decide an entry's terminal state and by
     * {@see KnowledgeEntry::scopeWithIndexedChunks()} to report progress. A second copy of it would
     * eventually disagree with the first, and the symptom would be a UI that says 8/8 for an entry the
     * indexer keeps re-running.
     *
     * PGSQL ONLY — `embedding` exists only where the chunks migration could add it. Callers check
     * {@see \App\Modules\Knowledge\Support\ChunkVector::supported()} first.
     */
    public function scopeIndexed(Builder $query): void
    {
        $query->whereRaw('embedding is not null')
            ->where('embedding_model', (string) config('knowledge.embedding.model'));
    }

    /**
     * Every column EXCEPT the vector. Use this for anything that lists or displays chunks — see the
     * class docblock for why hydrating `embedding` is a mistake rather than a preference.
     */
    public function scopeWithoutEmbedding(Builder $query): void
    {
        $query->select([
            'id',
            'knowledge_entry_id',
            'knowledge_base_id',
            'ordinal',
            'heading_path',
            'content',
            'char_start',
            'char_length',
            'digest',
            'embedding_model',
            'indexed_at',
            'created_at',
            'updated_at',
        ]);
    }

    protected static function newFactory()
    {
        return \Database\Factories\KnowledgeEntryChunkFactory::new();
    }
}
